openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
servers:
  - url: http://localhost:4000
    description: Development server

# securitySchemes:
#   bearerAuth: 
#     type: http
#     scheme: bearer
#     bearerFormat: JWT 

#header set 
# securitySchemes:
#     api_key:
#       type: apiKey
#       name: abc
#       in: header

components:
  securitySchemes:
    bearerAuth: 
      type: http
      scheme: bearer
      bearerFormat: JWT 

paths:
  /secret:
    get:
      summary: Get secret data
      security:
        - bearerAuth: []
      # parameters:
      #   - name: abc
      #     in: header
      #     description: ''
      #     required: false
      #     schema:
      #       type: string 
      responses:
        200:
          description: OK
  /public:
    get:
      summary: Get public data
      responses:
        200:
          description: OK
  /login:
    post:
      summary: Get public data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                  example: 1
      responses:
        200:
          description: token
